test_that("charToBib works ok", {

    ## Rcore <- format(citation(), style = "bibtex")
    ## ## add a citation key
    ## Rcore <- sub("\\@Manual\\{", "\\@Manual{Rcore", Rcore)
    ## cat(Rcore, sep = "\n")
    ## beRcore <- charToBib(Rcore)
    ## beRcore
    ## class(beRcore)
    ## print(beRcore, style = "R")

    ## Rcore is a bibtex string, without cite key. 
    bibRcore <- toBibtex(citation())
    be1 <- charToBib(bibRcore)
    be2 <- charToBib(bibRcore, direct = TRUE)
    ## some fields are renamed or dropped when direct is FALSE
    expect_equal(be1$publisher, be2$organization) # "R Foundation for Statistical Computing"
    
    ## with cite key
    txtRcore1 <- c(  
        "@Manual{Rcore,",                                                      
        "  title = {R: A Language and Environment for Statistical Computing},",
        "  author = {{R Core Team}},",
        "  organization = {R Foundation for Statistical Computing},",
        "  address = {Vienna, Austria},",
        "  year = {2020},",
        "  url = {https://www.R-project.org/},",
        "}" )

    txtRcore2 <- paste0(txtRcore1, collapse = " ")

    beRcore1 <- charToBib(txtRcore1)
    beRcore2 <- charToBib(txtRcore2)
    expect_equal(beRcore1, beRcore2)

    fn <- tempfile(fileext = ".bib")
    on.exit(unlink(fn))
    charToBib(txtRcore1, informat = "bibtex", outfile = fn)

    ## bibtex entries generated by citation() don't have cite keys.
    ## this sets the key to 'Rcore'
    beRcore <- charToBib(toBibtex(citation()), key = "Rcore")
    expect_equal(beRcore$key, "Rcore")

    ## this sets two keys
    bemore <- charToBib(toBibtex( c(citation(), citation("rbibutils"))),
                        key = c("Rcore", "Rpackage:rbibutils"))
    expect_equal(names(bemore), c("Rcore", "Rpackage:rbibutils"))
    
})
