bibentry(bibtype = "Article",
         key = "beachanddavidson1983",
         author = c(person(given = c("Charles", "M"),
                           family = "Beach",
                           role = "aut"),
                    person(given = "Russell",
                           family = "Davidson",
                           role = "aut")),
         title = "Distribution-free statistical inference with Lorenz curves and income shares",
         year = "1983",
         month = "02",
         genre = "periodical",
         journal = "Review of Economic Studies",
         citekey = "beachanddavidson1983",
         volume = "50",
         pages = "723--735")

bibentry(bibtype = "Article",
         key = "beachandkaliski1986a",
         author = c(person(given = c("C", "M"),
                           family = "Beach",
                           role = "aut"),
                    person(given = c("S", "F"),
                           family = "Kaliski",
                           role = "aut")),
         title = "Lorenz curve inference with sample weights: an application to the distribution of unemployment experience",
         year = "1986",
         genre = "periodical",
         journal = "Appl. Statist.",
         citekey = "beachandkaliski1986a",
         volume = "35",
         pages = "38--45")

bibentry(bibtype = "Book",
         key = "lambert1993",
         author = person(given = c("Peter", "J"),
                         family = "Lambert",
                         role = "aut"),
         title = "The distribution and redistribution of income. A mathematical analysis",
         publisher = "Manchester University Press, Manchester",
         institution = "Manchester University Press, Manchester",
         year = "1993",
         edition = "2",
         citekey = "lambert1993")

